# Generated by Django 2.2.3 on 2019-08-06 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_added_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='menu_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
