# Generated by Django 2.2.4 on 2019-08-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20190807_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('CART', 'In Cart'), ('PEND', 'Pending'), ('CONF', 'Confirmed'), ('DLVR', 'Delivered'), ('DONE', 'Completed')], default='CART', max_length=4),
        ),
    ]
