# Generated by Django 2.2.4 on 2019-08-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20190808_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('CART', 'In Cart'), ('PAID', 'Paid'), ('CONF', 'Confirmed'), ('DLVR', 'Delivered'), ('DONE', 'Completed')], default='CART', max_length=4),
        ),
    ]
