# Generated by Django 2.2.4 on 2019-08-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_checkoutitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutitem',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('CONF', 'Confirmed'), ('DLVR', 'Delivered'), ('DONE', 'Completed')], default='PAID', max_length=4),
        ),
    ]
