# Generated by Django 2.2.3 on 2019-07-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subextra',
            old_name='large',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='subextra',
            name='small',
        ),
    ]
