# Generated by Django 2.2.3 on 2019-08-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190706_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularpizza',
            name='toppingsCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='toppingsCount',
            field=models.IntegerField(default=0),
        ),
    ]
